<footer class="clearfix container"><!-- Defining the footer section of the page -->
  <section id="privacy">
    Marco Annunziata &copy; 2024 <a class="link" href="http://www.unife.it/">Universit&agrave; degli Studi di Ferrara</a><br />
    <a class="link" href="https://unife.coursecatalogue.cineca.it/insegnamenti/2023/13672/2018/2/10533?coorte=2021&schemaid=11507">Ingegneria dei Sistemi Web</a>
  </section>
</footer>