<script>
</script>

<header class="clearfix container">
  <a class="inline-block" href="Dispatcher?controllerAction=HomeManagement.view">
    <img src="<%=request.getContextPath()%>/assets/images/logo-cropped.png" alt="logo" width="125" height="125">
  </a>
  <a class="inline-block" href="Dispatcher?controllerAction=HomeManagement.view">
    <img class="logo-text" src="<%=request.getContextPath()%>/assets/images/logo-text.png" alt="logo" height="75">
  </a>
  <%@include file="navbar.inc"%>

</header>